wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.45.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.15
    start_time: 1731620916.546624
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 2
      - 16
      - 23
      4: 3.10.15
      5: 0.13.10
      6: 4.45.1
      8:
      - 2
      - 5
    visualize:
      confusion_matrix:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: confusion_matrix_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
model:
  desc: null
  value: gpt2-medium
